# Performance Measurement of Digital Image Processing: Evaluation of Sensitivity, Specificity, Accuracy, False Positive, and False Negative
___

## Performance Measurement

In [1]:
import numpy as np

### Question 1:  Evaluation of Image Comparison Metrics

In [2]:
realImage1 = np.array([
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1],
    [0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1]
])

resultImage1 = np.array([
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1]
])

In [3]:
print(realImage1)

[[0 0 0 0 0 1 1 0 0 0 0 0]
 [1 1 1 0 0 1 1 1 0 0 0 0]
 [1 1 1 0 0 1 1 1 0 0 0 0]
 [1 1 1 0 0 1 1 1 0 0 0 0]
 [0 0 1 0 0 1 1 1 0 1 1 1]
 [0 0 1 0 0 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 0 1 1 1 1 1]
 [0 0 1 1 1 1 0 1 1 1 1 1]
 [0 0 1 1 1 1 0 0 0 1 1 1]
 [0 0 1 1 1 1 0 0 0 1 1 1]]


In [4]:
print(resultImage1)

[[0 0 0 0 0 1 1 0 0 0 0 0]
 [1 1 1 0 0 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 1]
 [0 0 1 1 1 1 0 0 0 1 1 1]
 [0 0 1 1 1 1 0 0 0 1 1 1]]


In [5]:
tp, tn, fn, fp = 0, 0, 0, 0

for i in range(realImage1.shape[0]):
    for j in range(realImage1.shape[1]):
        if realImage1[i][j] == 1 and resultImage1[i][j] == 1:
            tp += 1
        elif realImage1[i][j] == 1 and resultImage1[i][j] != 1:
            fn += 1
        elif realImage1[i][j] != 1 and resultImage1[i][j] == 1:
            fp += 1
        elif realImage1[i][j] != 1 and resultImage1[i][j] != 1:
            tn += 1

print(f'''
      Sensitivity = {tp / (tp + fn) * 100}
      Specificity = {tn / (fp + tn) * 100}
      Accuracy    = {(tp + tn) / (tp + tn + fp + fn) * 100}
      FP          = {fp / (tp + tn + fp + fn) * 100}
      FN          = {fn / (tp + tn + fp + fn) * 100}
      ''')


      Sensitivity = 91.04477611940298
      Specificity = 77.35849056603774
      Accuracy    = 85.0
      FP          = 10.0
      FN          = 5.0
      


### Question 2: Evaluation of Image Intensity Comparison Metrics

In [6]:
realImage2 = np.array([
    [20, 40, 20, 40, 150, 240, 150, 240],
    [30, 35, 30, 35, 200, 250, 200, 250],
    [40, 48, 40, 48, 180, 241, 20, 40],
    [10, 39, 10, 39, 190, 160, 30, 35],
    [50, 23, 150, 240, 150, 240, 150, 240],
    [20, 40, 200, 250, 200, 250, 200, 250],
    [30, 35, 180, 241, 20, 40, 20, 40],
    [40, 48, 190, 160, 30, 35, 30, 35],
    [10, 39, 150, 240, 150, 240, 40, 48],
    [50, 23, 200, 250, 200, 250, 10, 39]
])

resultImage2 = np.array([
    [180, 241, 20, 40, 150, 240, 150, 240],
    [190, 160, 30, 35, 200, 250, 200, 250],
    [150, 240, 40, 48, 180, 241, 20, 40],
    [200, 250, 10, 39, 190, 20, 40, 20],
    [180, 241, 150, 240, 150, 30, 35, 30],
    [20, 40, 200, 250, 200, 40, 48, 40],
    [30, 35, 180, 241, 20, 40, 20, 40],
    [40, 48, 190, 160, 30, 35, 30, 35],
    [10, 39, 150, 240, 150, 240, 40, 48],
    [50, 23, 200, 250, 200, 250, 10, 39]
])

In [7]:
print(realImage2)

[[ 20  40  20  40 150 240 150 240]
 [ 30  35  30  35 200 250 200 250]
 [ 40  48  40  48 180 241  20  40]
 [ 10  39  10  39 190 160  30  35]
 [ 50  23 150 240 150 240 150 240]
 [ 20  40 200 250 200 250 200 250]
 [ 30  35 180 241  20  40  20  40]
 [ 40  48 190 160  30  35  30  35]
 [ 10  39 150 240 150 240  40  48]
 [ 50  23 200 250 200 250  10  39]]


In [8]:
print(resultImage2)

[[180 241  20  40 150 240 150 240]
 [190 160  30  35 200 250 200 250]
 [150 240  40  48 180 241  20  40]
 [200 250  10  39 190  20  40  20]
 [180 241 150 240 150  30  35  30]
 [ 20  40 200 250 200  40  48  40]
 [ 30  35 180 241  20  40  20  40]
 [ 40  48 190 160  30  35  30  35]
 [ 10  39 150 240 150 240  40  48]
 [ 50  23 200 250 200 250  10  39]]


In [9]:
tp, tn, fn, fp = 0, 0, 0, 0

for i in range(realImage2.shape[0]):
    for j in range(realImage2.shape[1]):
        if realImage2[i][j] >= 100 and resultImage2[i][j] >= 100:
            tp += 1
        elif realImage2[i][j] >= 100 and resultImage2[i][j] < 100:
            fn += 1
        elif realImage2[i][j] < 100 and resultImage2[i][j] >= 100:
            fp += 1
        elif realImage2[i][j] < 100 and resultImage2[i][j] < 100:
            tn += 1

print(f'''
      Sensitivity = {tp / (tp + fn) * 100}
      Specificity = {tn / (fp + tn) * 100}
      Accuracy    = {(tp + tn) / (tp + tn + fp + fn) * 100}
      FP          = {fp / (tp + tn + fp + fn) * 100}
      FN          = {fn / (tp + tn + fp + fn) * 100}
      ''')


      Sensitivity = 80.55555555555556
      Specificity = 77.27272727272727
      Accuracy    = 78.75
      FP          = 12.5
      FN          = 8.75
      
